vich_uploader:
    db_driver: orm

    mappings:
       recipes:
           uri_prefix: /recipes/images
           upload_destination: '%kernel.project_dir%/public/recipes/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
