controllers:
    prefix: "{_locale}"
    requirements:
        _locale: fr|en
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# home:
#     path: /
#     controller: App\Controller\HomeController::index
